codecov:
  require_ci_to_pass: false
  bot: hirotomoyamada
  ci:
    - github-actions

coverage:
  status:
    project:
      default:
        information: true
    patch:
      default:
        information: true
# comment:
#   layout: "reach, diff, files, components"
#   behavior: default
#   require_changes: false
